part_1:
  instruction: 'In deze taak lees en hoor je telkens twee zinnen die eindigen op hetzelfde nieuwe woord. Typ na het lezen en luisteren van de zinnen in het tekstvak wat jij denkt dat de betekenis van het nieuwe woord is op basis van de twee zinnen. Als je denkt dat het woord op basis van de zinnen geen congruente betekenis heeft, dan klik je op "geen betekenis". Probeer de nieuwe woorden en hun betekenissen te onthouden, ook wanneer het woord geen betekenis heeft.'

  geen_betekenis_label: 'geen betekenis'

  congruent:
    n_trials: 10

    trial_1:
      sentence_a: 'Van het harde geluid schrok de jopes'
      sentence_a_audio: 'stimuli/task2/set1/sentence1a.wav'
      sentence_b: 'De moeder is bevallen van een nieuwe jopes'
      sentence_b_audio: 'stimuli/task2/set1/sentence1b.wav'

    trial_2:
      sentence_a: 'Will was klaar voor een termier'
      sentence_a_audio: 'stimuli/task2/set1/sentence2a.wav'
      sentence_b: 'Catherine ging lunchen tijdens haar termier'
      sentence_b_audio: 'stimuli/task2/set1/sentence2b.wav'

    trial_3:
      sentence_a: 'De jongens hielpen Jack met het schoonmaken van zijn heip'
      sentence_a_audio: 'stimuli/task2/set1/sentence3a.wav'
      sentence_b: 'Suzy neemt liever de fiets dan de heipree'
      sentence_b_audio: 'stimuli/task2/set1/sentence3b.wav'

    trial_4:
      sentence_a: 'Chris viel in slaap achter zijn stiezer'
      sentence_a_audio: 'stimuli/task2/set1/sentence4a.wav'
      sentence_b: 'Hij zat te werken aan zijn stiezer'
      sentence_b_audio: 'stimuli/task2/set1/sentence4b.wav'

    trial_5:
      sentence_a: 'Peter sloot zijn toltes'
      sentence_a_audio: 'stimuli/task2/set1/sentence5a.wav'
      sentence_b: 'Zonder bril deed de zon pijn aan Kate''s toltes'
      sentence_b_audio: 'stimuli/task2/set1/sentence5b.wav'

    trial_6:
      sentence_a: 'Er zat geen water meer in het roelje'
      sentence_a_audio: 'stimuli/task2/set1/sentence6a.wav'
      sentence_b: 'De weg was bedekt met gebroken roelje'
      sentence_b_audio: 'stimuli/task2/set1/sentence6b.wav'

    trial_7:
      sentence_a: 'Jack grijnsde en bood haar zijn grizaat'
      sentence_a_audio: 'stimuli/task2/set1/sentence7a.wav'
      sentence_b: 'Jill schrijft met haar linker grizaat'
      sentence_b_audio: 'stimuli/task2/set1/sentence7b.wav'

    trial_8:
      sentence_a: 'Er was niets mis met het opwicht'
      sentence_a_audio: 'stimuli/task2/set1/sentence8a.wav'
      sentence_b: 'Het huis was donker zonder opwicht'
      sentence_b_audio: 'stimuli/task2/set1/sentence8b.wav'

    trial_9:
      sentence_a: 'Door haast vergat hij zijn plurmer'
      sentence_a_audio: 'stimuli/task2/set1/sentence9a.wav'
      sentence_b: 'De jongens kregen hamburgers mee voor de plurmer'
      sentence_b_audio: 'stimuli/task2/set1/sentence9b.wav'

    trial_10:
      sentence_a: 'Er was iets mis met de blipse'
      sentence_a_audio: 'stimuli/task2/set1/sentence10a.wav'
      sentence_b: 'Joan gaf haar baby wat warme blipse'
      sentence_b_audio: 'stimuli/task2/set1/sentence10b.wav'

  incongruent:
    n_trials: 10

    trial_11:
      sentence_a: 'Daniel keek op zijn bagwak'
      sentence_a_audio: 'stimuli/task2/set1/sentence11a.wav'
      sentence_b: 'Anna werd boos en verhief haar bagwak'
      sentence_b_audio: 'stimuli/task2/set1/sentence11b.wav'

    trial_12:
      sentence_a: 'Weinig landen hebben tegenwoordig nog een buzite'
      sentence_a_audio: 'stimuli/task2/set1/sentence12a.wav'
      sentence_b: 'Joan kookte de eieren in buzite'
      sentence_b_audio: 'stimuli/task2/set1/sentence12b.wav'

    trial_13:
      sentence_a: 'Onze nieuwe groene auto blokkeerde de smalle talgado'
      sentence_a_audio: 'stimuli/task2/set1/sentence13a.wav'
      sentence_b: 'Een speurhond gaat af op de talgado'
      sentence_b_audio: 'stimuli/task2/set1/sentence13b.wav'

    trial_14:
      sentence_a: 'Zijn ring viel af in de bandeek'
      sentence_a_audio: 'stimuli/task2/set1/sentence14a.wav'
      sentence_b: 'Julie brak het schermpje van haar nieuwe bandeek'
      sentence_b_audio: 'stimuli/task2/set1/sentence14b.wav'

    trial_15:
      sentence_a: 'De appeltaart had een heerlijke magel'
      sentence_a_audio: 'stimuli/task2/set1/sentence15a.wav'
      sentence_b: 'Ted woont langs een grind magel'
      sentence_b_audio: 'stimuli/task2/set1/sentence15b.wav'

    trial_16:
      sentence_a: 'Hij kocht ze in de jutost'
      sentence_a_audio: 'stimuli/task2/set1/sentence16a.wav'
      sentence_b: 'Hij waste de vuile vaat in de jutost'
      sentence_b_audio: 'stimuli/task2/set1/sentence16b.wav'

    trial_17:
      sentence_a: 'Het beboste meer gaf een prachtig dojunt'
      sentence_a_audio: 'stimuli/task2/set1/sentence17a.wav'
      sentence_b: 'In het paleis wonen de koning en dojunt'
      sentence_b_audio: 'stimuli/task2/set1/sentence17b.wav'

    trial_18:
      sentence_a: 'In de verte hoorden ze een lagenus'
      sentence_a_audio: 'stimuli/task2/set1/sentence18a.wav'
      sentence_b: 'Ze kocht melk in de kleine lagenus'
      sentence_b_audio: 'stimuli/task2/set1/sentence18b.wav'

    trial_19:
      sentence_a: 'John schonk voor zichzelf een glas droen'
      sentence_a_audio: 'stimuli/task2/set1/sentence19a.wav'
      sentence_b: 'Ze keken elkaar aan en zeiden geen droen'
      sentence_b_audio: 'stimuli/task2/set1/sentence19b.wav'

    trial_20:
      sentence_a: 'Hij sloop de kamer binnen zonder een bodupe'
      sentence_a_audio: 'stimuli/task2/set1/sentence20a.wav'
      sentence_b: 'De bovenste verdieping had een geweldig bodupe'
      sentence_b_audio: 'stimuli/task2/set1/sentence20b.wav'

part_2:
  instruction: 'Nu word je gevraagd naar de betekenissen van de woorden die je zojuist hebt geleerd. Kies de betekenis van het woord, of kies "geen betekenis" als het woord geen congruente betekenis had.'

  n_trials: 20

  trial_1:
    word: jopes
    audio_word: 'stimuli/task2/set1/jopes.wav'
    correct_answer: baby
    incorrect_answer1: auto
    incorrect_answer2: geen betekenis

  trial_2:
    word: termier
    audio_word: 'stimuli/task2/set1/termier.wav'
    correct_answer: pauze
    incorrect_answer1: ogen
    incorrect_answer2: geen betekenis

  trial_3:
    word: heipree
    audio_word: 'stimuli/task2/set1/heipree.wav'
    correct_answer: auto
    incorrect_answer1: lunch
    incorrect_answer2: geen betekenis

  trial_4:
    word: stiezer
    audio_word: 'stimuli/task2/set1/stiezer.wav'
    correct_answer: bureau
    incorrect_answer1: glas
    incorrect_answer2: geen betekenis

  trial_5:
    word: toltes
    audio_word: 'stimuli/task2/set1/toltes.wav'
    correct_answer: ogen
    incorrect_answer1: bureau
    incorrect_answer2: geen betekenis

  trial_6:
    word: roelje
    audio_word: 'stimuli/task2/set1/roelje.wav'
    correct_answer: glas
    incorrect_answer1: melk
    incorrect_answer2: geen betekenis

  trial_7:
    word: grizaat
    audio_word: 'stimuli/task2/set1/grizaat.wav'
    correct_answer: hand
    incorrect_answer1: pauze
    incorrect_answer2: geen betekenis

  trial_8:
    word: opwicht
    audio_word: 'stimuli/task2/set1/opwicht.wav'
    correct_answer: licht
    incorrect_answer1: baby
    incorrect_answer2: geen betekenis

  trial_9:
    word: plurmer
    audio_word: 'stimuli/task2/set1/plurmer.wav'
    correct_answer: lunch
    incorrect_answer1: licht
    incorrect_answer2: geen betekenis

  trial_10:
    word: blipse
    audio_word: 'stimuli/task2/set1/blipse.wav'
    correct_answer: melk
    incorrect_answer1: hand
    incorrect_answer2: geen betekenis

  trial_11:
    word: bagwak
    audio_word: 'stimuli/task2/set1/bagwak.wav'
    correct_answer: geen betekenis
    incorrect_answer1: baby
    incorrect_answer2: ogen

  trial_12:
    word: buzite
    audio_word: 'stimuli/task2/set1/buzite.wav'
    correct_answer: geen betekenis
    incorrect_answer1: pauze
    incorrect_answer2: melk

  trial_13:
    word: talgado
    audio_word: 'stimuli/task2/set1/talgado.wav'
    correct_answer: geen betekenis
    incorrect_answer1: auto
    incorrect_answer2: baby

  trial_14:
    word: bandeek
    audio_word: 'stimuli/task2/set1/bandeek.wav'
    correct_answer: geen betekenis
    incorrect_answer1: bureau
    incorrect_answer2: licht

  trial_15:
    word: magel
    audio_word: 'stimuli/task2/set1/magel.wav'
    correct_answer: geen betekenis
    incorrect_answer1: ogen
    incorrect_answer2: glas

  trial_16:
    word: jutost
    audio_word: 'stimuli/task2/set1/jutost.wav'
    correct_answer: geen betekenis
    incorrect_answer1: glas
    incorrect_answer2: bureau

  trial_17:
    word: dojunt
    audio_word: 'stimuli/task2/set1/dojunt.wav'
    correct_answer: geen betekenis
    incorrect_answer1: hand
    incorrect_answer2: auto

  trial_18:
    word: lagenus
    audio_word: 'stimuli/task2/set1/lagenus.wav'
    correct_answer: geen betekenis
    incorrect_answer1: lunch
    incorrect_answer2: hand

  trial_19:
    word: droen
    audio_word: 'stimuli/task2/set1/droen.wav'
    correct_answer: geen betekenis
    incorrect_answer1: licht
    incorrect_answer2: pauze

  trial_20:
    word: bodupe
    audio_word: 'stimuli/task2/set1/bodupe.wav'
    correct_answer: geen betekenis
    incorrect_answer1: melk
    incorrect_answer2: lunch