monitor:
  name: 'my_lab_monitor'
  width_cm: 55.9
  distance_cm: 60.0
  width_px: 1680
  height_px: 1050

window:
  size: [1080, 720]
  units: deg
  fullscreen: true

colors:
  background: white
  text: black
  accent: blue
  success: green
  muted: gray

audio:
  backends: [sounddevice, pygame]

# experiment params that have to do with both sets
task_1:
  exit_instruction: 'Dit was het einde van deze taak. Druk op de spatiebalk om af te sluiten'
  test_trials_part_1: 1
  test_trials_part_2: 1

task_2:
  exit_instruction: 'Dit was het einde van deze taak. Druk op de spatiebalk om af te sluiten'
  test_trials_part_1: 1
  test_trials_part_2: 1

# rating instruction
rating_instruction: "Hoe zeker ben je van je keuze? 1: Ik gokte 4: Ik herinner het me. \n Druk op 1-4 om te kiezen, Enter om te bevestigen"
